name: Vet
on: [push]

jobs:
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run vet
        run: go vet ./...